### ISSUE TITLE
Status-Feld macht gelegentlich Probleme

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_usability#71]
Undefined variable: istatus
#0 /home/users/xxx/www/redaxo/src/addons/yform_usability/lib/Utils.php(66): rex_error_handler::handleError()
#1 /home/users/xxx/www/redaxo/src/addons/yform_usability/lib/Extensions.php(90): yform\usability\Utils::getStatusColumnParams()
#2 /home/users/xxx/www/redaxo/src/core/lib/util/formatter.php(353): yform\usability\Extensions::yform\usability\{closure}()
#3 /home/users/xxx/www/redaxo/src/core/lib/util/formatter.php(33): rex_formatter::custom()
#4 /home/users/xxx/www/redaxo/src/core/lib/list.php(950): rex_formatter::format()
#5 /home/users/xxx/www/redaxo/src/core/lib/list.php(1103): rex_list->formatValue()
#6 /home/users/xxx/www/redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php(697): rex_list->get()
#7 /home/users/xxx/www/redaxo/src/addons/yform/plugins/manager/pages/data_edit.php(20): rex_yform_manager->getDataPage()
#8 /home/users/xxx/www/redaxo/src/core/lib/packages/package.php(250): include('/home/users/mar...')
#9 /home/users/xxx/www/redaxo/src/core/lib/be/controller.php(476): rex_package->includeFile()
#10 /home/users/xxx/www/redaxo/src/core/lib/util/timer.php(54): rex_be_controller::{closure}()
#11 /home/users/xxx/www/redaxo/src/core/lib/be/controller.php(477): rex_timer::measure()
#12 /home/users/xxx/www/redaxo/src/core/lib/be/controller.php(432): rex_be_controller::includePath()
#13 /home/users/xxx/www/redaxo/src/addons/yform/pages/index.php(6): rex_be_controller::includeCurrentPageSubPath()
#14 /home/users/xxx/www/redaxo/src/core/lib/packages/package.php(250): include('/home/users/mar...')
#15 /home/users/xxx/www/redaxo/src/core/lib/be/controller.php(476): rex_package->includeFile()
#16 /home/users/xxx/www/redaxo/src/core/lib/util/timer.php(54): rex_be_controller::{closure}()
#17 /home/users/xxx/www/redaxo/src/core/lib/be/controller.php(477): rex_timer::measure()
#18 /home/users/xxx/www/redaxo/src/core/lib/be/controller.php(415): rex_be_controller::includePath()
#19 /home/users/xxx/www/redaxo/src/core/backend.php(235): rex_be_controller::includeCurrentPage()
#20 /home/users/xxx/www/redaxo/src/core/boot.php(137): require('/home/users/mar...')
#21 /home/users/xxx/www/redaxo/index.php(9): require('/home/users/mar...')
#22 {main}

Man bekommt keinen Whoops und es ist unklar, wie man es reproduzieren kann - kann aber einfach auftauchen bei einer Tabelle.

**Comment by alxndr-w** [comment]
Hatte ich seit Monaten nicht mehr. Könnte ein Folgefehler gewesen sein.
